package timeshift

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

// Backend performs a repository's file operations. Local is the filesystem;
// SSH runs the same operations as commands over a multiplexed connection.
//
// Only the read surface is here so far; the write half arrives with snapshot
// creation.
type Backend interface {
	IsRemote() bool
	DisplayName() string
	TypeID() string

	DirExists(ctx context.Context, p string) bool
	FileExists(ctx context.Context, p string) bool
	ReadFile(ctx context.Context, p string) ([]byte, error)

	// ListSubdirs returns the immediate subdirectory names of p.
	//
	// An empty result means "no subdirectories" ONLY when the error is nil. A
	// transport failure must be an error: SnapshotRepo.load_snapshots() learned
	// this the hard way, because a dropped SSH link made every snapshot read as
	// invalid and auto_remove() then deleted the whole repository.
	ListSubdirs(ctx context.Context, p string) ([]string, error)

	// QuerySpace reports the filesystem holding p.
	QuerySpace(ctx context.Context, p string) (size, used, available uint64, err error)

	// ReadControlFiles fetches several files from each of several snapshot
	// directories. Local backends read them one by one; the SSH backend batches
	// the lot into a single round trip, because a repository with fifty
	// snapshots would otherwise mean two hundred and fifty of them.
	ReadControlFiles(ctx context.Context, dirs []string, names []string) (map[string]string, error)

	// TestConnection reports whether the repository is reachable.
	TestConnection(ctx context.Context) (string, error)

	// MakeDir creates a directory and its parents.
	MakeDir(ctx context.Context, p string) error

	// WriteFile writes a file, replacing it if it exists.
	WriteFile(ctx context.Context, p string, data []byte) error

	// RemoveCommand is the argv that deletes a tree verbosely, so progress can
	// be counted from its output.
	RemoveCommand(p string) []string

	// Remove deletes a tree without reporting progress.
	Remove(ctx context.Context, p string) error

	// Close releases anything held open, such as an SSH master connection.
	Close() error
}

// Runner is the command surface a backend needs.
type Runner interface {
	Run(ctx context.Context, argv []string, stdin string) (exitCode int, stdout, stderr string, err error)
}

// ---------------------------------------------------------------- local ----

// LocalBackend is a repository on a mounted filesystem.
type LocalBackend struct {
	Runner Runner
	Name   string
}

func (b *LocalBackend) IsRemote() bool      { return false }
func (b *LocalBackend) TypeID() string      { return "local" }
func (b *LocalBackend) DisplayName() string { return b.Name }
func (b *LocalBackend) Close() error        { return nil }

func (b *LocalBackend) DirExists(_ context.Context, p string) bool {
	fi, err := os.Stat(p)
	return err == nil && fi.IsDir()
}

func (b *LocalBackend) FileExists(_ context.Context, p string) bool {
	fi, err := os.Lstat(p)
	return err == nil && !fi.IsDir()
}

func (b *LocalBackend) ReadFile(_ context.Context, p string) ([]byte, error) {
	return os.ReadFile(p)
}

func (b *LocalBackend) ListSubdirs(_ context.Context, p string) ([]string, error) {
	entries, err := os.ReadDir(p)
	if err != nil {
		return nil, fmt.Errorf("timeshift: list %s: %w", p, err)
	}
	var out []string
	for _, e := range entries {
		if e.IsDir() {
			out = append(out, e.Name())
		}
	}
	return out, nil
}

func (b *LocalBackend) QuerySpace(ctx context.Context, p string) (uint64, uint64, uint64, error) {
	code, stdout, stderr, err := b.Runner.Run(ctx, []string{"df", "-B1", p}, "")
	if err != nil {
		return 0, 0, 0, err
	}
	if code != 0 {
		return 0, 0, 0, fmt.Errorf("timeshift: df exited %d: %s", code, strings.TrimSpace(stderr))
	}
	return parseDFLine(stdout)
}

func (b *LocalBackend) ReadControlFiles(ctx context.Context, dirs, names []string) (map[string]string, error) {
	out := map[string]string{}
	for _, dir := range dirs {
		for _, name := range names {
			p := filepath.Join(dir, name)
			if data, err := os.ReadFile(p); err == nil {
				out[dir+"\x00"+name] = string(data)
			}
		}
	}
	return out, nil
}

func (b *LocalBackend) TestConnection(_ context.Context) (string, error) { return "", nil }

// ------------------------------------------------------------------ ssh ----

// SSHBackend is a repository on another host, reached with ssh and rsync.
type SSHBackend struct {
	Runner Runner

	User string
	Host string
	Port int
	Path string

	KeyFile   string
	FakeSuper bool

	// ControlPath is the multiplexing socket. Empty disables multiplexing.
	ControlPath string
}

// KeyDir holds the key Timeshift manages and the known_hosts of remotes the
// user has explicitly confirmed. Beside timeshift.json rather than in root's
// personal ~/.ssh, so it is obviously app-owned.
const KeyDir = "/etc/timeshift/ssh"

// DefaultKeyFile is the key generated by --setup-ssh-key.
func DefaultKeyFile() string { return path.Join(KeyDir, "id_ed25519") }

// KnownHostsFile is the host-key store for repositories.
func KnownHostsFile() string { return path.Join(KeyDir, "known_hosts") }

func (b *SSHBackend) IsRemote() bool { return true }
func (b *SSHBackend) TypeID() string { return "remote-ssh-rsync" }

// DisplayName is "user@host", which is what the CLI prints as Remote.
func (b *SSHBackend) DisplayName() string {
	if b.User == "" {
		return b.Host
	}
	return b.User + "@" + b.Host
}

// HostSpec is the argument ssh and rsync take.
func (b *SSHBackend) HostSpec() string { return b.DisplayName() }

var safeHostComponent = regexp.MustCompile(`^[A-Za-z0-9._-]+$`)

// IsSafeHostComponent rejects anything that could be mistaken for an ssh
// option, and anything outside what a hostname or username may contain.
//
// This is a security control, not tidiness. The host and user are passed to ssh
// as arguments, and a value beginning with "-" is parsed as an OPTION -- so a
// URL like ssh://-oProxyCommand=.../path runs an arbitrary command as root.
// Verified behaviour, not theoretical.
//
// IPv6 literals are rejected rather than mis-parsed: the bracket form confuses
// the host:port split, and silently connecting to the wrong host is worse than
// refusing to connect at all.
func IsSafeHostComponent(v string) bool {
	if v == "" || strings.HasPrefix(v, "-") {
		return false
	}
	return safeHostComponent.MatchString(v)
}

// ErrBadURL is returned for a repository URL that cannot be used.
var ErrBadURL = errors.New("timeshift: repository URL must be ssh://[user@]host[:port]/path or [user@]host:/path")

// ParseURL splits a remote repository URL.
//
// Two forms are accepted, matching RepoBackend.parse_url():
//
//	ssh://[user@]host[:port]/path   -- split at the first / after the scheme
//	[user@]host:/path               -- split at the FIRST colon, no port
func ParseURL(url string) (user, host string, port int, p string, err error) {
	port = 22
	rest := strings.TrimSpace(url)

	if after, ok := strings.CutPrefix(rest, "ssh://"); ok {
		rest = after
		slash := strings.Index(rest, "/")
		if slash < 0 {
			return "", "", 0, "", ErrBadURL
		}
		authority := rest[:slash]
		p = rest[slash:]

		if at := strings.LastIndex(authority, "@"); at >= 0 {
			user = authority[:at]
			authority = authority[at+1:]
		}
		if colon := strings.LastIndex(authority, ":"); colon >= 0 {
			port, _ = strconv.Atoi(authority[colon+1:])
			authority = authority[:colon]
		}
		host = authority
	} else {
		colon := strings.Index(rest, ":")
		if colon < 0 {
			return "", "", 0, "", ErrBadURL
		}
		authority := rest[:colon]
		p = rest[colon+1:]
		if at := strings.LastIndex(authority, "@"); at >= 0 {
			user = authority[:at]
			authority = authority[at+1:]
		}
		host = authority
	}

	if host == "" || p == "" || !strings.HasPrefix(p, "/") {
		return "", "", 0, "", ErrBadURL
	}
	if !IsSafeHostComponent(host) {
		return "", "", 0, "", fmt.Errorf("%w: unsafe host %q", ErrBadURL, host)
	}
	if user != "" && !IsSafeHostComponent(user) {
		return "", "", 0, "", fmt.Errorf("%w: unsafe user %q", ErrBadURL, user)
	}
	return user, host, port, p, nil
}

// SSHOptions builds the option list every ssh invocation shares.
//
// stdinUsed omits -n, which otherwise stops ssh consuming Timeshift's own
// stdin. noMux forces a fresh connection instead of attaching to the shared
// ControlMaster socket -- which matters because a client attaching to a wedged
// master over its unix socket never calls connect(2), so ConnectTimeout does
// not apply and it simply blocks forever. That is exactly how a recovered
// network still looked unreachable.
func (b *SSHBackend) SSHOptions(stdinUsed, noMux bool) []string {
	opts := []string{
		// Verify against the hosts the user confirmed during setup, and keep
		// root's personal known_hosts out of it.
		"-o", "BatchMode=yes",
		"-o", "StrictHostKeyChecking=accept-new",
		// Without ConnectTimeout a firewalled host blocks for the kernel's SYN
		// retry budget, around 130 seconds; without ServerAlive* a link that
		// dies mid-operation never returns at all.
		"-o", "ConnectTimeout=10",
		"-o", "ServerAliveInterval=15",
		"-o", "ServerAliveCountMax=3",
	}
	if !stdinUsed {
		opts = append(opts, "-n")
	}
	opts = append(opts,
		// With keys in an agent ssh may offer those first and hit MaxAuthTries
		// before ever trying -i.
		"-o", "IdentitiesOnly=yes",
		// root's ssh_config must not be able to rewrite the host, the
		// ControlPath, or inject a ProxyCommand.
		"-F", "/dev/null",
		"-o", "UserKnownHostsFile="+KnownHostsFile(),
	)
	if b.Port != 0 && b.Port != 22 {
		opts = append(opts, "-p", strconv.Itoa(b.Port))
	}
	if b.KeyFile != "" {
		opts = append(opts, "-i", b.KeyFile)
	}
	if noMux {
		opts = append(opts, "-o", "ControlMaster=no", "-o", "ControlPath=none")
	} else if b.ControlPath != "" {
		opts = append(opts,
			"-o", "ControlMaster=auto",
			"-o", "ControlPath="+b.ControlPath,
			"-o", "ControlPersist=60")
	}
	return opts
}

// remote runs one shell command on the remote host and returns its output.
//
// The command reaches the remote shell as a single argument, so it -- and only
// it -- has to be shell-safe. Everything on this side is an argv element.
func (b *SSHBackend) remote(ctx context.Context, command string) (int, string, string, error) {
	argv := append([]string{"ssh"}, b.SSHOptions(false, false)...)
	argv = append(argv, b.HostSpec(), command)
	return b.Runner.Run(ctx, argv, "")
}

func (b *SSHBackend) DirExists(ctx context.Context, p string) bool {
	code, _, _, err := b.remote(ctx, "test -d "+shellQuote(p))
	return err == nil && code == 0
}

func (b *SSHBackend) FileExists(ctx context.Context, p string) bool {
	code, _, _, err := b.remote(ctx, "test -f "+shellQuote(p))
	return err == nil && code == 0
}

func (b *SSHBackend) ReadFile(ctx context.Context, p string) ([]byte, error) {
	code, stdout, stderr, err := b.remote(ctx, "cat "+shellQuote(p))
	if err != nil {
		return nil, err
	}
	if code != 0 {
		return nil, fmt.Errorf("timeshift: read %s: %s", p, strings.TrimSpace(stderr))
	}
	return []byte(stdout), nil
}

func (b *SSHBackend) ListSubdirs(ctx context.Context, p string) ([]string, error) {
	/* -1 one per line, -A to include dotted names, -p to append / to
	 * directories -- which is how a directory is told from a file without a
	 * second round trip. */
	code, stdout, stderr, err := b.remote(ctx, "ls -1Ap "+shellQuote(p))
	if err != nil {
		return nil, fmt.Errorf("timeshift: list %s: %w", p, err)
	}
	if code != 0 {
		return nil, fmt.Errorf("timeshift: list %s: ssh exited %d: %s",
			p, code, strings.TrimSpace(stderr))
	}
	var out []string
	for _, line := range strings.Split(stdout, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasSuffix(line, "/") {
			out = append(out, strings.TrimSuffix(line, "/"))
		}
	}
	return out, nil
}

func (b *SSHBackend) QuerySpace(ctx context.Context, p string) (uint64, uint64, uint64, error) {
	code, stdout, stderr, err := b.remote(ctx, "df -B1 "+shellQuote(p))
	if err != nil {
		return 0, 0, 0, err
	}
	if code != 0 {
		return 0, 0, 0, fmt.Errorf("timeshift: remote df exited %d: %s", code, strings.TrimSpace(stderr))
	}
	return parseDFLine(stdout)
}

/* The batched prefetch. One `cat` per file across every snapshot would be a
 * round trip each; a repository with fifty snapshots and five control files is
 * two hundred and fifty of them, over a link that may be a home broadband
 * connection. Instead one command emits every file with a delimiter, and the
 * whole listing arrives in a single exchange. */
const controlDelimiter = "@@TS_FILE:"

func (b *SSHBackend) ReadControlFiles(ctx context.Context, dirs, names []string) (map[string]string, error) {
	if len(dirs) == 0 || len(names) == 0 {
		return map[string]string{}, nil
	}

	var script strings.Builder
	for _, dir := range dirs {
		for _, name := range names {
			p := path.Join(dir, name)
			/* The marker is emitted only when the file is actually readable,
			 * so absence is a missing key rather than an empty section. The
			 * distinction matters: `cat` of a nonexistent file and `cat` of a
			 * file holding one newline produce identical bytes, and an
			 * exclude.list that reads as present-but-empty marks an rsync
			 * snapshot valid when it is not. */
			fmt.Fprintf(&script, "if [ -r %s ]; then echo '%s%s'; cat %s; echo; fi; ",
				shellQuote(p), controlDelimiter, dir+"\x01"+name, shellQuote(p))
		}
	}

	code, stdout, stderr, err := b.remote(ctx, script.String())
	if err != nil {
		return nil, fmt.Errorf("timeshift: prefetch control files: %w", err)
	}
	if code != 0 {
		return nil, fmt.Errorf("timeshift: prefetch control files: ssh exited %d: %s",
			code, strings.TrimSpace(stderr))
	}

	return parseControlBatch(stdout), nil
}

// parseControlBatch splits the delimited stream back into files.
func parseControlBatch(out string) map[string]string {
	files := map[string]string{}
	var key string
	var body strings.Builder

	flush := func() {
		if key == "" {
			return
		}
		/* Strip exactly one trailing newline: the `echo` that terminates each
		 * section. Whatever the file itself ended with survives, so the content
		 * is byte-identical to the remote file. */
		text := strings.TrimSuffix(body.String(), "\n")
		if parts := strings.SplitN(key, "\x01", 2); len(parts) == 2 {
			files[parts[0]+"\x00"+parts[1]] = text
		}
		key = ""
		body.Reset()
	}

	/* Drop the newline that terminates the stream as a whole before splitting,
	 * or the final section picks up a phantom empty line and keeps a newline
	 * that was never in the file. */
	for _, line := range strings.Split(strings.TrimSuffix(out, "\n"), "\n") {
		if marker, ok := strings.CutPrefix(line, controlDelimiter); ok {
			flush()
			key = marker
			continue
		}
		if key != "" {
			body.WriteString(line)
			body.WriteByte('\n')
		}
	}
	flush()
	return files
}

func (b *SSHBackend) TestConnection(ctx context.Context) (string, error) {
	code, _, stderr, err := b.remote(ctx, "true")
	if err != nil {
		return err.Error(), err
	}
	if code != 0 {
		msg := strings.TrimSpace(stderr)
		if msg == "" {
			msg = fmt.Sprintf("ssh exited %d", code)
		}
		return msg, fmt.Errorf("timeshift: cannot reach %s: %s", b.HostSpec(), msg)
	}
	return "", nil
}

// Close drops the multiplexed master connection.
func (b *SSHBackend) Close() error {
	if b.ControlPath == "" {
		return nil
	}
	argv := append([]string{"ssh"}, b.SSHOptions(false, false)...)
	argv = append(argv, "-O", "exit", b.HostSpec())
	b.Runner.Run(context.Background(), argv, "")
	return nil
}

// --------------------------------------------------------------- shared ----

// parseDFLine reads the data row of `df -B1` output.
func parseDFLine(out string) (size, used, available uint64, err error) {
	lines := strings.Split(strings.TrimSpace(out), "\n")
	if len(lines) < 2 {
		return 0, 0, 0, fmt.Errorf("timeshift: unreadable df output: %q", out)
	}
	/* A long device name wraps onto its own line, so the figures are the LAST
	 * four fields before the mount point rather than fields 2..4 of the row. */
	f := strings.Fields(lines[len(lines)-1])
	if len(f) < 4 {
		return 0, 0, 0, fmt.Errorf("timeshift: unreadable df row: %q", lines[len(lines)-1])
	}
	base := len(f) - 5
	if base < 0 {
		base = len(f) - 4
	}
	if base < 0 {
		return 0, 0, 0, fmt.Errorf("timeshift: unreadable df row: %q", lines[len(lines)-1])
	}
	size, _ = strconv.ParseUint(f[base], 10, 64)
	used, _ = strconv.ParseUint(f[base+1], 10, 64)
	available, _ = strconv.ParseUint(f[base+2], 10, 64)
	return size, used, available, nil
}

// shellQuote wraps a value for the remote shell. Only remote commands need it:
// everything local is an argv element.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

/* The write surface.
 *
 * Separated from the read methods above because the read path landed first and
 * because a future read-only backend -- an archive being browsed, say -- can
 * implement one without the other.
 */

// MakeDir creates a directory and its parents.
func (b *LocalBackend) MakeDir(ctx context.Context, p string) error {
	return os.MkdirAll(p, 0755)
}

// WriteFile writes a file, replacing it if it exists.
func (b *LocalBackend) WriteFile(ctx context.Context, p string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(p), 0755); err != nil {
		return err
	}
	return os.WriteFile(p, data, 0644)
}

// RemoveCommand is the argv that removes a directory tree, one line of output
// per path so progress can be counted.
func (b *LocalBackend) RemoveCommand(p string) []string {
	return []string{"rm", "-rfv", p}
}

// Remove deletes a directory tree.
func (b *LocalBackend) Remove(ctx context.Context, p string) error {
	return os.RemoveAll(p)
}

func (b *SSHBackend) MakeDir(ctx context.Context, p string) error {
	code, _, stderr, err := b.remote(ctx, "mkdir -p "+shellQuote(p))
	if err != nil {
		return err
	}
	if code != 0 {
		return fmt.Errorf("timeshift: mkdir %s: %s", p, strings.TrimSpace(stderr))
	}
	return nil
}

// WriteFile pipes the content through ssh's stdin.
//
// stdinUsed is true in SSHOptions, which drops -n. With -n ssh reads from
// /dev/null and the remote file comes out empty -- silently, and only
// discovered when a restore has nothing to exclude.
func (b *SSHBackend) WriteFile(ctx context.Context, p string, data []byte) error {
	argv := append([]string{"ssh"}, b.SSHOptions(true, false)...)
	argv = append(argv, b.HostSpec(),
		"mkdir -p "+shellQuote(path.Dir(p))+" && cat > "+shellQuote(p))
	code, _, stderr, err := b.Runner.Run(ctx, argv, string(data))
	if err != nil {
		return err
	}
	if code != 0 {
		return fmt.Errorf("timeshift: write %s: %s", p, strings.TrimSpace(stderr))
	}
	return nil
}

func (b *SSHBackend) RemoveCommand(p string) []string {
	argv := append([]string{"ssh"}, b.SSHOptions(false, false)...)
	return append(argv, b.HostSpec(), "rm -rfv "+shellQuote(p))
}

func (b *SSHBackend) Remove(ctx context.Context, p string) error {
	code, _, stderr, err := b.remote(ctx, "rm -rf "+shellQuote(p))
	if err != nil {
		return err
	}
	if code != 0 {
		return fmt.Errorf("timeshift: remove %s: %s", p, strings.TrimSpace(stderr))
	}
	return nil
}
