#!/usr/bin/env bash

app_command='timeshift-gtk'

if [[ "$(id -u)" -eq 0 ]]; then
	# user is admin
	exec "${app_command}" "$@"
else
	# user is not admin
	if echo $- | grep "i" >/dev/null 2>&1; then
		# script is running in interactive mode
		exec su - -c "${app_command}" "$@"
	else
		# script is running in non-interactive mode
		if command -v pkexec >/dev/null 2>&1; then
			env_array=("GTK_THEME=${GTK_THEME}")

			if [[ "${XDG_SESSION_TYPE}" == "wayland" ]]; then
				env_array+=("WAYLAND_DISPLAY=${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}" "XDG_RUNTIME_DIR=/run/user/0")
			else
				env_array+=("DISPLAY=${DISPLAY}" "XAUTHORITY=${XAUTHORITY}")
			fi

			exec pkexec env "${env_array[@]}" "${app_command}" "$@"
		elif command -v sudo >/dev/null 2>&1; then
			exec sudo -E "${app_command}" "$@"
		elif command -v su >/dev/null 2>&1; then
			exec su - -c "${app_command}" "$@"
		else
			echo "Command must be run as root user: ${app_command}"
		fi
	fi
fi
